export const ROOM_STATUS_OCCUPIED = "OCCUPIED"
export const ROOM_STATUS_UNSANITIZED = "UNSANITIZED"
export const ROOM_STATUS_SANITIZED = "SANITIZED"
export const ROOM_STATUS_VACANT = "VACANT"
export const ROOM_STATUS_CLEANING = "CLEANING"

export const ROOM_STATUS_OCCUPIED_COLOR = "rgba(237, 78, 63, 0.92)"
export const ROOM_STATUS_UNSANITIZED_COLOR = "rgba(177, 179, 178, 0.92)"
export const ROOM_STATUS_SANITIZED_COLOR = "rgba(108, 220, 248, 0.92)"
export const ROOM_STATUS_VACANT_COLOR = "rgba(108, 248, 136, 0.92)"
export const ROOM_STATUS_CLEANING_COLOR = "rgba(108, 150, 248, 0.92)"

